site_name: lingyu's notes

nav:
  - Home: index.md
  - Python: 
    - PythonBasic:
      - 语言/Python/Python-100-Days/PythonBasic/01.初识Python.md
      - 语言/Python/Python-100-Days/PythonBasic/02.语言元素.md
      - 语言/Python/Python-100-Days/PythonBasic/03.分支结构.md
      - 语言/Python/Python-100-Days/PythonBasic/04.循环结构.md
      - 语言/Python/Python-100-Days/PythonBasic/05.构造程序逻辑.md
      - 语言/Python/Python-100-Days/PythonBasic/06.函数和模块的使用.md
      - 语言/Python/Python-100-Days/PythonBasic/07.字符串和常用数据结构.md
      - 语言/Python/Python-100-Days/PythonBasic/08.面向对象编程基础.md
      - 语言/Python/Python-100-Days/PythonBasic/09.面向对象进阶.md
      - 语言/Python/Python-100-Days/PythonBasic/10.图形用户界面和游戏开发.md
      - 语言/Python/Python-100-Days/PythonBasic/11.文件和异常.md
      - 语言/Python/Python-100-Days/PythonBasic/12.字符串和正则表达式.md
      - 语言/Python/Python-100-Days/PythonBasic/13.进程和线程.md
      - 语言/Python/Python-100-Days/PythonBasic/14.网络编程入门和网络应用开发.md
      - 语言/Python/Python-100-Days/PythonBasic/15.图像和办公文档处理.md
    - Python进阶:
      - 语言/Python/Python-100-Days/Python进阶/16.Python语言进阶.md
    - DataAnalysis:
      - 语言/Python/Python-100-Days/DataAnalysis/66.数据分析概述.md
      - 语言/Python/Python-100-Days/DataAnalysis/67.环境准备.md
      - 语言/Python/Python-100-Days/DataAnalysis/68.NumPy的应用-1.md
      - 语言/Python/Python-100-Days/DataAnalysis/69.NumPy的应用-2.md
      - 语言/Python/Python-100-Days/DataAnalysis/70.NumPy的应用-3.md
      - 语言/Python/Python-100-Days/DataAnalysis/71.NumPy的应用-4.md
      - 语言/Python/Python-100-Days/DataAnalysis/72.深入浅出pandas-1.md
      - 语言/Python/Python-100-Days/DataAnalysis/73.深入浅出pandas-2.md
      - 语言/Python/Python-100-Days/DataAnalysis/74.深入浅出pandas-3.md
      - 语言/Python/Python-100-Days/DataAnalysis/75.深入浅出pandas-4.md
      - 语言/Python/Python-100-Days/DataAnalysis/76.深入浅出pandas-5.md
      - 语言/Python/Python-100-Days/DataAnalysis/77.深入浅出pandas-6.md
      - 语言/Python/Python-100-Days/DataAnalysis/78.数据可视化-1.md
      - 语言/Python/Python-100-Days/DataAnalysis/79.数据可视化-2.md
      - 语言/Python/Python-100-Days/DataAnalysis/80.数据可视化-3.md
      - 语言/Python/jupyter/Python数据分析-numpy.ipynb
      - 语言/Python/jupyter/Python数据分析-pandas.ipynb
    - 语言/Python/PythonCookBook.md
    - 语言/Python/PythonforDataAnalysis3E.md
    - 语言/Python/PythonMisc.md
  - C: 语言/C/C.md
  - C++: 
    - 语言/Cpp/Cpp_primer.md
    - 语言/Cpp/Essential_Cpp.md
  - ICS: 
        - ICS/ICS_Lectures.md
        - ICS/ICS_Lab.md
  - OS: 
        - OS/绪论.md
        - OS/并发.md
        - OS/虚拟化.md
        - OS/持久化.md
        - OS/总结.md
        - OS/Lab.md
        - OS/OSTEP.md
        - OS/CodingForSSD.md
        - OS/SJTU_OS.md
  - 数据结构: data_structure.md
  - 算法: 
    - DS_Algo/leetcode.md
  - Linux: 
      - 基础知识: Linux/Linux.md
      - Useful cmd: Linux/useful_cmd.md
      - 玩转Linux操作系统: Linux/玩转Linux操作系统.md
  - 计算机网络: network.md
  - 数据库: database.md
  - Tool: Tool/tool.md
  - Misc: 
      - Memo: Misc/Memo.md
      - Todo: Misc/Todo.md

theme:
  icon:
    logo: material/notebook-outline
  language: zh
  name: material
  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    - content.code.annotate
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    # - content.action.edit
  palette:
    # Toggle light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Toggle dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

repo_url: https://github.com/lingyu11/notes/tree/master
repo_name: lingyu11/notes

extra:
  generator: false

copyright: Copyright &copy; lingyu CC-BY-4.0

# [Extensions]
plugins:
  - mkdocs-jupyter
  # [搜索功能]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # 之前中文搜索是 Insider 的功能（https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/），现在好像已经是默认功能了，
  - search:
      lang:
        - zh
        - en
        - ja
  # - localsearch
  # [给单篇文章添加标签]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/#meta.tags
  # - tags
  # - statistics
  - changelog
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
markdown_extensions:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - pymdownx.arithmatex:
      generic: true
  # [图片功能支持]
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  # 给 Markdown 图片语法后面添加 `{width="300"}` 设置大小
  - attr_list
  - md_in_html
  # [给标题添加链接]
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.permalink
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # [代码语法高亮]
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      # 显示行号
      linenums: true
      # 显示编程语言名称
      # auto_title: true
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.line_spans
      line_spans: __span
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.pygments_lang_class
      pygments_lang_class: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # [Markdown 提示]
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  # [Markdown footnote 语法支持]
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes

extra_javascript:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  # [自定义 css]
  # 不使用底部的翻页
  - mkdocs/css/no-footer.css
  # 无序列表符号自定义
  - mkdocs/css/unordered-list-symbols.css
  - css/table.css